### ISSUE TITLE
`kubectl exec -ti $POD_NAME -- nginx -v` results in `Error from server (NotFound): deployments.apps "nginx" not found`

### ISSUE THREAD

**Issue by Dzhuneyt** [jamesward/kubernetes-the-easy-way#3]
Following the steps from https://github.com/jamesward/kubernetes-the-easy-way/blob/master/docs/13-smoke-test.md I get:
```
❯ kubectl expose deployment nginx --port 80 --type NodePort

Error from server (NotFound): deployments.apps "nginx" not found
```

**Comment by Dzhuneyt** [comment]
Fixed it by running `kubectl create deployment nginx --image=nginx` instead of `kubectl run ...` as described in previous steps. I guess `kubectl run ...` is kind of deprecated or something.

**Comment by jamesward** [comment]
Thanks for reporting this. I've made updates to resolve this.
